name: CI
on:
  push:
    pull_request:
      - main

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      # - run: npx nx format:check
      - run: npm install nx@16.3.2 --no-save
      - run: nx print-affected --base=origin/main --head=origin/add-ci
      # - run: npx nx affected --base=origin/main --head=origin/add-ci -t lint --parallel=3
      # - run: npx nx affected -t test --parallel=3 --configuration=ci
      # - run: npx nx affected -t build --parallel=3
